#ifndef LIGHTPADLIB_GLOBAL_H
#define LIGHTPADLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIGHTPADLIB_LIBRARY)
#  define LIGHTPADLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIGHTPADLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTPADLIB_GLOBAL_H
