---
Information:
  Type: ColorScheme
  Name: Monokai

Window:
  Background: 272822
  Foreground: E8E8E3

Line:
  Highlighter: 49483E
  Selected: A6E22E
  ColumnNumbers: 8F908A
  Column: 2F312B

Syntax: 
  Character: E6DB74
  Comment: 75715E
  Argument: FD971F
  Error: FF0000
  ExtendedKeywords: F92672
  BuiltinFunctions: 66D9EF
  Keyword: 66D9EF
  Method: A6E22E
  Number: AE81FF
  Operator: F92672
  String: E6DB74
  URL: AE81FF
  Warning: FFFF00
...